[package]
name = "web_scrape"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.20"
tokio = { version = "1.45.1", features = ["full"] }
scraper = "0.23.1"
smart-default = "0.7.1"
rand_agents = "1.0.0"